name: RSS to README

on:
  schedule:
    - cron: '0 */1 * * *' # 매 시간 정각에 실행
  push:
    branches:
      - main # 지정한 브랜치에 push 할 때 워크플로우 실행
  workflow_dispatch: # 수동 트리거 기능 활성

jobs:
  update-readme:
    runs-on: ubuntu-latest
    timeout-minutes: 30 # 워크플로우가 30분 내에 완료되지 않으면 자동 종료

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_committer_name: ColorFilter
          git_committer_email: johan@romantech.net
          trust_level: 5 # Ultimate

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: latest
          run_install: true

      - name: Run update script
        run: pnpm rss-to-readme # 업데이트 스크립트 실행

      - name: Commit README
        run: |
          # Git 저장소에 변경사항이 있을 때만 명령어 실행
          if [ -n "$(git status --porcelain)" ]; then
            git add README.md
            git commit -m "Update README with latest blog posts [auto-generated]" -m "Generated at: $(date '+%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No changes to commit"
          fi
